import type { OrderSummary } from "./types";

export const orders: OrderSummary[] = [
  {
    id: "SL-1024",
    customer: "Anjali Rao",
    phone: "+91 98765 43210",
    article: "Custom embroidered blouse",
    source: "Phone",
    total: 2450,
    dueDate: "2026-07-22",
    orderStatus: "Confirmed",
    productionStatus: "Stitching",
    paymentStatus: "Advance paid",
    mediaStatus: "Not required",
  },
  {
    id: "SL-1025",
    customer: "Meera Reddy",
    phone: "+91 91234 56789",
    article: "Green Anarkali dress",
    source: "Instagram",
    total: 4999,
    dueDate: "2026-07-20",
    orderStatus: "Confirmed",
    productionStatus: "Ready for photography",
    paymentStatus: "Paid",
    mediaStatus: "Photography pending",
  },
  {
    id: "SL-1026",
    customer: "Suma Devi",
    phone: "+91 99887 77665",
    article: "Ready-made kurti — M",
    source: "Website",
    total: 1499,
    dueDate: "2026-07-19",
    orderStatus: "Confirmed",
    productionStatus: "Completed",
    paymentStatus: "COD pending",
    mediaStatus: "Published",
  },
];

export const inventory = [
  {
    code: "FAB-COT-BLU-001",
    name: "Blue cotton fabric",
    unit: "metre",
    onHand: 42.5,
    reserved: 8,
    reorder: 15,
  },
  {
    code: "FAB-SIL-MAR-002",
    name: "Maroon silk fabric",
    unit: "metre",
    onHand: 9.5,
    reserved: 6,
    reorder: 12,
  },
  {
    code: "ACC-HOOK-001",
    name: "Blouse hooks",
    unit: "piece",
    onHand: 260,
    reserved: 48,
    reorder: 100,
  },
  {
    code: "PKG-BAG-001",
    name: "Branded garment bag",
    unit: "piece",
    onHand: 36,
    reserved: 14,
    reorder: 50,
  },
];
